### ISSUE TITLE
Error, most probably java

### ISSUE THREAD

**Issue by tushar-ahmed** [Dulab2020/AutoVEM2#1]
I have installed Autovem2 in a complete separate conda environment but still facing the problem. Could you please help??
OpenJDK 8.0.332  was automatically installed during installation with your conda command. then I tried with OpenJDK 11 but faced the same issue

For more information about these sites, please view the haplo/rsva/snp_sites.tsv file
Done!
Obtaining reference haplotype sequence and data.tsv file...
Done!
Obtaining block.txt file...
Done!
Obtaining map file...
Done!
Obtaining snp.ped file...
Done!
Linkage analyzing...
*****************************************************
Haploview 4.2	Java Version: 1.8.0_332
*****************************************************

Arguments:	-n	-skipcheck	-pedfile	haplo/rsva/snp.ped	-info	haplo/rsva/snp.info	-blocks	haplo/rsva/block.txt	-png	-out	haplo/rsva/plot	

Skipping genotype file check
Using data file: haplo/rsva/snp.ped
Using output fileroot: haplo/rsva/plot
Using marker information file: haplo/rsva/snp.info
Writing output to plot.CUSTblocks
Using custom blocks file: haplo/rsva/block.txt
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at edu.mit.wi.haploview.HaploData.pickTags(HaploData.java:1170)
	at edu.mit.wi.haploview.HaploText.processFile(HaploText.java:1629)
	at edu.mit.wi.haploview.HaploText.processTextOnly(HaploText.java:1369)
	at edu.mit.wi.haploview.HaploText.<init>(HaploText.java:245)
	at edu.mit.wi.haploview.HaploView.main(HaploView.java:1600)
Done!
Haplotyping......
Traceback (most recent call last):
  File "/home/admin-lab/miniconda3/envs/autovem/bin/autovem2", line 277, in <module>
    args.func(args)
  File "/home/admin-lab/miniconda3/envs/autovem/bin/autovem2", line 230, in pipeline_func
    dataPlot = analysis.module2(snpFile, outDir, ref, sites=sites, frequency=frequency)
  File "/home/admin-lab/miniconda3/envs/autovem/bin/analysis.py", line 636, in module2
    data_plot = haplotyper(haplotypesFile, dataFile, directory)
  File "/home/admin-lab/miniconda3/envs/autovem/bin/analysis.py", line 394, in haplotyper
    with open(file, 'r') as fhand:
FileNotFoundError: [Errno 2] No such file or directory: 'haplo/rsva/plot.CUSTblocks'

**Comment by tushar-ahmed** [comment]
to let you know,

I have tried Autovem with openjdk-8. It worked but not working for Autovem2
haploview tool was always the same in both cases. If the problem is with Java compatibility then how it is working in autovem but not in autovem2?

**Comment by Dulab2020** [comment]
Thank you for your feedback! we have updated AutoVEM2. You could try again and see whether it works by using the provided example.

**Comment by elserj** [comment]
I am doing the exact same thing of trying to use this for RSV and having the same issue as @tushar-ahmed. I'm guessing it was solved eventually as I can see the paper that was published, but I have not been able to figure out how to fix this.

I've narrowed it down to the actual array of haplotypes in Haploview.jar is empty, but I'm not sure why.

Can you please share any info you have on fixing this?

Thanks in advance.
